In [2]:
# Basic Python code

l1=[2,3,54,1]
l2=[1,2,1,100]
print(l1+l2)

[2, 3, 54, 1, 1, 2, 1, 100]


In [18]:
# import numpy as np
c=np.array([[23,44,33,9],[2,1,3,2]])
print(c[0:2, 1:4])

# print(c[1:3,0:2])

[[44 33  9]
 [ 1  3  2]]


In [15]:

# Numpy basics in 


import numpy as np
s=np.array([11,22,33,44])
r=np.array([12,24,36,48])
print(s)
print(np.size(s))
print(s.dtype)
print(np.sqrt(r))
print(np.add(s,r)) 
# print(s+r) or of above

print(np.concatenate([s,r])) 
# square bracker or 2 brackets in concatenate


[11 22 33 44]
4
int64
[3.46410162 4.89897949 6.         6.92820323]
[23 46 69 92]
[11 22 33 44 12 24 36 48]


In [6]:
# concept of vertical and horizontal axis
import numpy as np
a=np.array([[2,4,6,8],[3,9,12,15]])
b=np.array([[1,2,3,4],[4,8,12,16]])
print(np.concatenate([a,b],axis=0))
print(np.concatenate([a,b],axis=1))
# or method 2 hstack and vstack
print("Now horizontal stack method")
# same as axis=1 for horziontal
print(np.hstack([a,b]))

print("Now vertical stack")
print(np.vstack([a,b]))


[[ 2  4  6  8]
 [ 3  9 12 15]
 [ 1  2  3  4]
 [ 4  8 12 16]]
[[ 2  4  6  8  1  2  3  4]
 [ 3  9 12 15  4  8 12 16]]
Now horizontal stack method
[[ 2  4  6  8  1  2  3  4]
 [ 3  9 12 15  4  8 12 16]]
Now vertical stack
[[ 2  4  6  8]
 [ 3  9 12 15]
 [ 1  2  3  4]
 [ 4  8 12 16]]


In [9]:
# Split array

a=np.array([1,2,4,5,5,8])
print(np.array_split(a,2))
b=np.array_split(a,2)
# split in 2  divisions and index 0 and 1 for that
print(b[1])



[array([1, 2, 4]), array([5, 5, 8])]
[5 5 8]


In [17]:
# append in arrays
a=np.array([[1,2,3],[3,4,5]])
print(np.append(a,[[90],[100]],axis=1))

[[  1   2   3  90]
 [  3   4   5 100]]


In [28]:
# insertion in arrays
a=np.array([[1,2,3],[3,4,5]])
print(np.insert(a,1,50))
# insertion using axis  in insert element place
print(np.insert(a,1,50,axis=0))

# 2d array insertion axis is necessary for 2d output
print(np.insert(a,1,[30,40],axis=1))

[ 1 50  2  3  3  4  5]
[[ 1  2  3]
 [50 50 50]
 [ 3  4  5]]
[[ 1 30  2  3]
 [ 3 40  4  5]]


In [30]:
# sorting in array
a=np.array([7,8,4,12,9])
print(np.sort(a))
# for 2d sorting
b=np.array([[12,3,22,43,4],[9,3,11,18,1]])
print(np.sort(b))

[ 4  7  8  9 12]
[[ 3  4 12 22 43]
 [ 1  3  9 11 18]]
